language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
- npm install karma
- npm install karma-jasmine
- npm install jasmine-core
- npm install karma-chrome-launcher
- npm install karma-coverage
- npm install karma-coveralls
- npm install karma-cli

# run tests with coverage
script:
- coverage run -m unittest discover -s src/test -p '*_test.py'
- karma start conf/karma.conf.js &

after_success:
- karma stop
- cat coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- coveralls
