language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls

# run tests with coverage
script: coverage erase
script: coverage run src/event_generator_test.py
script: coverage run src/push_server_test.py
script: coverage report

after_success: coveralls