language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls

# run tests with coverage
script: coverage run -p src/event_generator_test.py && coverage run -p src/push_server_test.py && coverage combine

after_success: coveralls